CREATE DATABASE STUDENTS;

USE STUDENTS;

CREATE TABLE  STUDENTS_INFO(
STUDENT_ID INT PRIMARY KEY,
STUDENT_NAME VARCHAR(100),
DEPARTMENTS VARCHAR(100),
AGE INT,
EMAIL VARCHAR(100));

INSERT INTO STUDENTS_INFO (STUDENT_ID, STUDENT_NAME, DEPARTMENTS, AGE, EMAIL)
VALUES
(1, 'Ravi',  'CS',  20, 'ravi.cs@univ.com'),
(2, 'Anita', 'IT',  21, 'anita.it@univ.com'),
(3, 'Kumar', 'CS',  22, 'kumar.cs@univ.com'),
(4, 'Priya', 'ECE', 20, '0'),
(5, 'Suresh','IT',  23, 'suresh.it@univ.com');

SELECT DISTINCT DEPARTMENTS
FROM STUDENTS_INFO;