CREATE DATABASE PATIENT_DETAILS;

USE PATIENT_DETAILS;

CREATE TABLE PATIENTS(
PATIENT_ID INT PRIMARY KEY,
PATIENT_NAME VARCHAR(100),
AGE INT,
GENDER VARCHAR(10),
ADMISSION_DATE DATE);

ALTER TABLE PATIENTS
ADD DOCTOR_ASSIGNED VARCHAR(50);

ALTER TABLE PATIENTS
MODIFY PATIENT_NAME VARCHAR(150);