CREATE DATABASE PATIENT_DETAILS;

CREATE TABLE PATIENTS(
PATIENTS_ID PRIMARY KEY,
PATIENTS_NAME(VARCHAR100),
AGE INT,
GENDER (VARCHAR10),
ADMISSION_DATE DATE);
DROP DATABASE PATIENT_DETAILS;
CREATE DATABASE PATIENT_DETAILS;

CREATE TABLE PATIENTS(
PATIENTS_ID PRIMARY KEY,
PATIENTS_NAME VARCHAR(100),
AGE INT,
GENDER (VARCHAR10),
ADMISSION_DATE DATE);
USE PATIENT_DETAILS;

ALTER TABLE PATIENTS
ADD DOCTOR_ASSIGNED VARCHAR(50);