CREATE DATABASE ONLINE_BOOKSTORE;

USE ONLINE_BOOKSTORE;
CREATE TABLE BOOKS(
BOOKS_ID INT PRIMARY KEY,
AUTHORS VARCHAR(100),
BOOK_TITLE VARCHAR(100),
PRICE DECIMAL(8,2));

CREATE TABLE ORDERS(
ORDER_ID INT PRIMARY KEY,
ORDER_DATE DATE,
BOOKS_ID INT,
FOREIGN KEY (BOOKS_ID) REFERENCES BOOKS (BOOKS_ID));